import { useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, Clock3, FileText, LoaderCircle, Plus, Send, Timer, XCircle } from "lucide-react";
import { api, type BootstrapData, type CompTimeRequest, type OvertimeCompensation, type OvertimeRequest, type OvertimeStatus } from "./api";

const statusLabels: Record<OvertimeStatus, string> = { draft: "草稿", human_reviewing: "审批中", approved: "已通过", rejected: "已驳回", withdrawn: "已撤回" };
type Tab = "mine" | "inbox" | "history"; type Section = "overtime" | "compTime";

export default function OvertimePage({ userId, data, onChanged }: { userId: string; data: BootstrapData; onChanged: () => Promise<void> }) {
  const [lists, setLists] = useState(data.overtimeRequests); const [section, setSection] = useState<Section>("overtime"); const [tab, setTab] = useState<Tab>(data.currentUser.permissions.approveLeave ? "inbox" : "mine"); const [showForm, setShowForm] = useState(false); const [showCompForm, setShowCompForm] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { setLists(await api.overtimeRequests(userId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "加班数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [userId]);
  async function run(operation: () => Promise<void>, success: string) { setError(""); setNotice(""); try { await operation(); setNotice(success); await load(); await onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败"); } }
  const items = lists[section][tab];
  return <>
    <div className="page-heading expense-heading"><div><span className="eyebrow">OVERTIME & COMP TIME</span><h1>加班与调休</h1><p>加班先审批，选择调休后自动累计余额；调休申请会在批准时扣减余额。</p></div><div className="page-heading-actions"><button className="button ghost" onClick={() => setShowCompForm(true)}><Plus size={16} />申请调休</button><button className="button primary" onClick={() => setShowForm(true)}><Plus size={17} />登记加班</button></div></div>
    <div className="balance-card overtime-balance"><Timer size={20} /><div><span>可用调休余额</span><strong>{lists.balance.toFixed(2)} 小时</strong></div></div>
    {error && <div className="form-error" role="alert"><XCircle size={16} />{error}</div>}{notice && <p className="pilot-success" role="status">{notice}</p>}
    <div className="expense-tabs" role="tablist"><button role="tab" aria-selected={section === "overtime"} onClick={() => setSection("overtime")}>加班申请</button><button role="tab" aria-selected={section === "compTime"} onClick={() => setSection("compTime")}>调休申请</button></div>
    <div className="expense-tabs" role="tablist">{(["mine", "inbox", "history"] as const).map(key => <button key={key} role="tab" aria-selected={tab === key} onClick={() => setTab(key)}>{key === "mine" ? "我的申请" : key === "inbox" ? "待我审批" : "已处理"}<span>{lists[section][key].length}</span></button>)}</div>
    {loading && <p className="muted"><LoaderCircle className="spin" size={16} /> 正在加载…</p>}
    <section className="expense-list">{section === "overtime" ? (items as OvertimeRequest[]).map(item => <OvertimeCard key={item.id} item={item} canDecide={tab === "inbox"} canSubmit={tab === "mine"} onDone={(action) => void run(async () => { if (action === "submit") await api.submitOvertime(userId, item.id, item.version); else if (action === "withdraw") await api.withdrawOvertime(userId, item.id, "申请人撤回"); else { const reason = window.prompt(action === "approve" ? "审批意见（可选）" : "驳回原因（必填）", action === "approve" ? "同意加班" : "请补充加班事由") ?? ""; await api.decideOvertime(userId, item.id, action, reason, item.version); } }, action === "submit" ? "加班申请已提交" : "审批操作已完成")} />) : (items as CompTimeRequest[]).map(item => <CompTimeCard key={item.id} item={item} canDecide={tab === "inbox"} canSubmit={tab === "mine"} onDone={(action) => void run(async () => { if (action === "submit") await api.submitCompTime(userId, item.id, item.version); else if (action === "withdraw") await api.withdrawCompTime(userId, item.id, "申请人撤回"); else { const reason = window.prompt(action === "approve" ? "审批意见（可选）" : "驳回原因（必填）", action === "approve" ? "同意调休" : "请补充调休日期和事由") ?? ""; await api.decideCompTime(userId, item.id, action, reason, item.version); } }, action === "submit" ? "调休申请已提交" : "审批操作已完成")} />)}{!items.length && <div className="empty-state"><Timer size={32} /><strong>{tab === "inbox" ? "暂无待审批申请" : "暂无申请记录"}</strong></div>}</section>
    {showForm && <OvertimeForm userId={userId} onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); void run(async () => undefined, "加班草稿已保存"); }} />}{showCompForm && <CompTimeForm userId={userId} onClose={() => setShowCompForm(false)} onCreated={() => { setShowCompForm(false); void run(async () => undefined, "调休草稿已保存"); }} />}
  </>;
}

function tone(status: OvertimeStatus) { return status === "approved" ? "success" : status === "rejected" || status === "withdrawn" ? "danger" : status === "draft" ? "neutral" : "warning"; }
function Actions({ item, canDecide, canSubmit, onDone }: { item: OvertimeRequest | CompTimeRequest; canDecide: boolean; canSubmit: boolean; onDone: (action: "submit" | "withdraw" | "approve" | "reject") => void }) { return <div className="expense-actions">{canSubmit && item.status === "draft" && <><button className="button primary" onClick={() => onDone("submit")}><Send size={14} />提交审批</button><button className="button ghost" onClick={() => onDone("withdraw")}>删除草稿</button></>}{canDecide && item.status === "human_reviewing" && <><button className="button primary" onClick={() => onDone("approve")}><CheckCircle2 size={14} />批准</button><button className="button danger-outline" onClick={() => onDone("reject")}><XCircle size={14} />驳回</button></>}</div>; }
function OvertimeCard({ item, canDecide, canSubmit, onDone }: { item: OvertimeRequest; canDecide: boolean; canSubmit: boolean; onDone: (action: "submit" | "withdraw" | "approve" | "reject") => void }) { return <article className="expense-card"><div className="expense-card-main"><span className={`expense-icon ${item.status}`}><Timer size={18} /></span><div><div className="expense-title"><strong>{item.hours.toFixed(2)} 小时加班 · {item.compensationType === "comp_leave" ? "调休" : "加班费"}</strong><span className={`status-badge ${tone(item.status)}`}>{statusLabels[item.status]}</span></div><p>{item.reason}</p><small>{item.applicantName} · {item.department} · {item.startAt.slice(0, 16).replace("T", " ")} 至 {item.endAt.slice(0, 16).replace("T", " ")}</small></div></div><Actions item={item} canDecide={canDecide} canSubmit={canSubmit} onDone={onDone} /></article>; }
function CompTimeCard({ item, canDecide, canSubmit, onDone }: { item: CompTimeRequest; canDecide: boolean; canSubmit: boolean; onDone: (action: "submit" | "withdraw" | "approve" | "reject") => void }) { return <article className="expense-card"><div className="expense-card-main"><span className={`expense-icon ${item.status}`}><Clock3 size={18} /></span><div><div className="expense-title"><strong>{item.hours.toFixed(2)} 小时调休 · {item.date}</strong><span className={`status-badge ${tone(item.status)}`}>{statusLabels[item.status]}</span></div><p>{item.reason}</p><small>{item.applicantName} · {item.department}</small></div></div><Actions item={item} canDecide={canDecide} canSubmit={canSubmit} onDone={onDone} /></article>; }

function OvertimeForm({ userId, onClose, onCreated }: { userId: string; onClose: () => void; onCreated: () => void }) { const [startAt, setStartAt] = useState(""); const [endAt, setEndAt] = useState(""); const [reason, setReason] = useState(""); const [compensationType, setCompensationType] = useState<OvertimeCompensation>("comp_leave"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api.createOvertime(userId, { startAt: startAt + ":00+08:00", endAt: endAt + ":00+08:00", reason, compensationType }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); } finally { setBusy(false); } } return <div className="expense-backdrop"><form className="expense-dialog" onSubmit={submit}><header><div><span className="eyebrow">NEW OVERTIME</span><h2>登记加班</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><XCircle size={18} /></button></header><div className="expense-form-grid"><label>开始时间<input required type="datetime-local" value={startAt} onChange={e => setStartAt(e.target.value)} /></label><label>结束时间<input required type="datetime-local" value={endAt} onChange={e => setEndAt(e.target.value)} /></label><label>补偿方式<select value={compensationType} onChange={e => setCompensationType(e.target.value as OvertimeCompensation)}><option value="comp_leave">调休</option><option value="pay">加班费</option></select></label><label className="full">加班事由<textarea required minLength={2} maxLength={2000} rows={4} value={reason} onChange={e => setReason(e.target.value)} /></label></div>{error && <div className="form-error"><XCircle size={15} />{error}</div>}<footer><span><Clock3 size={14} />系统按起止时间计算小时数</span><button type="button" className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={15} /> : <FileText size={15} />}保存草稿</button></footer></form></div>; }
function CompTimeForm({ userId, onClose, onCreated }: { userId: string; onClose: () => void; onCreated: () => void }) { const [date, setDate] = useState(""); const [hours, setHours] = useState(""); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api.createCompTime(userId, { date, hours: Number(hours), reason }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); } finally { setBusy(false); } } return <div className="expense-backdrop"><form className="expense-dialog" onSubmit={submit}><header><div><span className="eyebrow">NEW COMP TIME</span><h2>申请调休</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><XCircle size={18} /></button></header><div className="expense-form-grid"><label>调休日期<input required type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label>调休时长（小时）<input required type="number" min="0.01" max="2000" step="0.01" value={hours} onChange={e => setHours(e.target.value)} /></label><label className="full">调休事由<textarea required minLength={2} maxLength={2000} rows={4} value={reason} onChange={e => setReason(e.target.value)} /></label></div>{error && <div className="form-error"><XCircle size={15} />{error}</div>}<footer><span><Clock3 size={14} />批准时会校验调休余额</span><button type="button" className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={15} /> : <FileText size={15} />}保存草稿</button></footer></form></div>; }
