import { useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, Clock3, FileText, LoaderCircle, Plus, Send, ShoppingCart, XCircle } from "lucide-react";
import { api, type BootstrapData, type ProcurementItem, type ProcurementRequest, type ProcurementStatus } from "./api";

const statusLabels: Record<ProcurementStatus, string> = { draft: "草稿", human_reviewing: "审批中", approved: "已通过", rejected: "已驳回", withdrawn: "已撤回" };
type Tab = "mine" | "inbox" | "history";

export default function ProcurementPage({ userId, data, onChanged }: { userId: string; data: BootstrapData; onChanged: () => Promise<void> }) {
  const [lists, setLists] = useState(data.procurementRequests);
  const [tab, setTab] = useState<Tab>(data.currentUser.permissions.approveLeave ? "inbox" : "mine");
  const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { setLists(await api.procurementRequests(userId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "采购数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [userId]);
  async function run(operation: () => Promise<void>, success: string) { setError(""); setNotice(""); try { await operation(); setNotice(success); await load(); await onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败"); } }
  const items = lists[tab];
  return <>
    <div className="page-heading expense-heading"><div><span className="eyebrow">PURCHASE REQUESTS</span><h1>采购申请</h1><p>采购明细、预算和审批意见在线留痕，便于采购执行和财务核对。</p></div><button className="button primary" onClick={() => setShowForm(true)}><Plus size={17} />新建采购</button></div>
    {error && <div className="form-error" role="alert"><XCircle size={16} />{error}</div>}{notice && <p className="pilot-success" role="status">{notice}</p>}
    <div className="expense-tabs" role="tablist">{(["mine", "inbox", "history"] as const).map(key => <button key={key} role="tab" aria-selected={tab === key} onClick={() => setTab(key)}>{key === "mine" ? "我的采购" : key === "inbox" ? "待我审批" : "已处理"}<span>{lists[key].length}</span></button>)}</div>
    {loading && <p className="muted"><LoaderCircle className="spin" size={16} /> 正在加载…</p>}
    <section className="expense-list">{items.map(item => <ProcurementCard key={item.id} item={item} canDecide={tab === "inbox"} canSubmit={tab === "mine"} onDone={(action) => void run(async () => { if (action === "submit") await api.submitProcurement(userId, item.id, item.version); else if (action === "withdraw") await api.withdrawProcurement(userId, item.id, "申请人撤回"); else { const reason = window.prompt(action === "approve" ? "审批意见（可选）" : "驳回原因（必填）", action === "approve" ? "同意采购" : "请补充采购用途和预算说明") ?? ""; await api.decideProcurement(userId, item.id, action, reason, item.version); } }, action === "submit" ? "采购申请已提交" : "审批操作已完成")} />)}{!items.length && <div className="empty-state"><ShoppingCart size={32} /><strong>{tab === "inbox" ? "暂无待审批采购" : "暂无采购记录"}</strong></div>}</section>
    {showForm && <ProcurementForm userId={userId} onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); void run(async () => undefined, "采购草稿已保存"); }} />}
  </>;
}

function ProcurementCard({ item, canDecide, canSubmit, onDone }: { item: ProcurementRequest; canDecide: boolean; canSubmit: boolean; onDone: (action: "submit" | "withdraw" | "approve" | "reject") => void }) {
  const tone = item.status === "approved" ? "success" : item.status === "rejected" || item.status === "withdrawn" ? "danger" : item.status === "draft" ? "neutral" : "warning";
  return <article className="expense-card"><div className="expense-card-main"><span className={`expense-icon ${item.status}`}><ShoppingCart size={18} /></span><div><div className="expense-title"><strong>{item.title} · {item.estimatedAmount.toFixed(2)} {item.currency}</strong><span className={`status-badge ${tone}`}>{statusLabels[item.status]}</span></div><p>{item.purpose} · {item.items.length} 项 · 预算 {item.budget.toFixed(2)} {item.currency}</p><small>{item.applicantName} · {item.department} · 需要日期 {item.needBy}{item.supplier ? ` · 供应商：${item.supplier}` : ""}</small></div></div><div className="expense-actions">{canSubmit && item.status === "draft" && <><button className="button primary" onClick={() => onDone("submit")}><Send size={14} />提交审批</button><button className="button ghost" onClick={() => onDone("withdraw")}>删除草稿</button></>}{canDecide && item.status === "human_reviewing" && <><button className="button primary" onClick={() => onDone("approve")}><CheckCircle2 size={14} />批准</button><button className="button danger-outline" onClick={() => onDone("reject")}><XCircle size={14} />驳回</button></>}</div></article>;
}

function ProcurementForm({ userId, onClose, onCreated }: { userId: string; onClose: () => void; onCreated: () => void }) {
  const [title, setTitle] = useState(""); const [purpose, setPurpose] = useState(""); const [budget, setBudget] = useState(""); const [supplier, setSupplier] = useState(""); const [needBy, setNeedBy] = useState(""); const [items, setItems] = useState<ProcurementItem[]>([{ name: "", quantity: 1, unitPrice: 0 }]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const estimated = items.reduce((total, item) => total + item.quantity * item.unitPrice, 0);
  function update(index: number, field: keyof ProcurementItem, value: string) { setItems(current => current.map((item, i) => i === index ? { ...item, [field]: field === "name" ? value : Number(value) } : item)); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { if (estimated > Number(budget)) throw new Error("预计采购金额不能超过预算"); await api.createProcurement(userId, { title, purpose, items, budget: Number(budget), currency: "CNY", supplier: supplier || null, needBy }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); } finally { setBusy(false); } }
  return <div className="expense-backdrop"><form className="expense-dialog" onSubmit={submit}><header><div><span className="eyebrow">NEW PURCHASE</span><h2>新建采购申请</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><XCircle size={18} /></button></header><div className="expense-form-grid"><label>采购标题<input required minLength={2} maxLength={200} value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：研发办公显示器" /></label><label>预算（元）<input required type="number" min="0.01" step="0.01" value={budget} onChange={e => setBudget(e.target.value)} /></label><label>需要日期<input required type="date" value={needBy} onChange={e => setNeedBy(e.target.value)} /></label><label>供应商（可选）<input value={supplier} onChange={e => setSupplier(e.target.value)} /></label><label className="full">采购用途<textarea required minLength={2} maxLength={2000} rows={3} value={purpose} onChange={e => setPurpose(e.target.value)} placeholder="说明项目、部门和使用场景" /></label><div className="full procurement-items"><div className="section-heading"><strong>采购明细</strong><span>预计合计：{estimated.toFixed(2)} 元</span></div>{items.map((item, index) => <div className="procurement-item-row" key={index}><input required placeholder="物品名称" value={item.name} onChange={e => update(index, "name", e.target.value)} /><input required type="number" min="0.01" step="0.01" placeholder="数量" value={item.quantity} onChange={e => update(index, "quantity", e.target.value)} /><input required type="number" min="0.01" step="0.01" placeholder="单价" value={item.unitPrice || ""} onChange={e => update(index, "unitPrice", e.target.value)} /><button type="button" className="button ghost" disabled={items.length === 1} onClick={() => setItems(current => current.filter((_, i) => i !== index))}>删除</button></div>)}<button type="button" className="button ghost" onClick={() => setItems(current => [...current, { name: "", quantity: 1, unitPrice: 0 }])}><Plus size={14} />添加明细</button></div></div>{error && <div className="form-error"><XCircle size={15} />{error}</div>}<footer><span><Clock3 size={14} />保存后可在列表中提交审批</span><button type="button" className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={15} /> : <FileText size={15} />}保存草稿</button></footer></form></div>;
}
